ImageServiceWeb/Controllers/WebController.cs
using ImageServiceWeb.Communication;
using ImageServiceWeb.Models;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;

namespace ImageServiceWeb.Controllers
{
    public class WebController : Controller
    {
        static LogModel l_model = new LogModel();
        static ConfigModel c_model = new ConfigModel();
        static HomePageModel h_model = new HomePageModel(c_model.configuration);
        static PhotosModel p_model = new PhotosModel(c_model.configuration);

        [HttpGet]
        public ActionResult HomePage()
        {
            HasConnection();
            return View(h_model.students);
        }

        public string NumberOfPics()
        {
            return h_model.numOfPics.ToString();
        }

        public string ServiceStatus()
        {
            return h_model.status;
        }

        [HttpGet]
        public ActionResult LogsView()
        {
            if (!HasConnection()) { return RedirectToAction("NoConnection"); }
            return View(l_model.logs);
        }

        [HttpGet]
        public ActionResult ConfigView()
        {
            if (!HasConnection()) { return RedirectToAction("NoConnection"); }
            return View(c_model.configuration);
        }

        [HttpPost]
        public ActionResult ConfigView(string item)
        {
            if (!HasConnection()) { return RedirectToAction("NoConnection"); }
            return RedirectToAction("RemoveHandlerView", new { item });
        }

        [HttpGet]
        public ActionResult RemoveHandlerView(string item)
        {
            if (!HasConnection()) { return RedirectToAction("NoConnection"); }
            ViewBag.handler = item;
            return View();
        }

        [HttpPost]
        public void RemoveHandler(string name)
        {
            c_model.RemoveHandler(name);
        }

        [HttpGet]
        public ActionResult PhotosView()
        {
            if (!HasConnection()) { return RedirectToAction("NoConnection"); }
            return View(p_model.PhotoList);
        }

        [HttpPost]
        public ActionResult DeletePicView(string path)
        {
            if (!HasConnection()) { return RedirectToAction("NoConnection"); }
            return View(new Photo(path));
        }

        [HttpPost]
        public void DeletePic(string path, string t_path)
        {
            // delete 2 pics, thumbnail and regular
            p_model.DeletePic(path);
            p_model.DeletePic(t_path);
        }

        [HttpPost]
        public ActionResult PicView(string path)
        {
            if (!HasConnection()) { return RedirectToAction("NoConnection"); }
            return View(new Photo(path));
        }

        public ActionResult NoConnection()
        {
            return View();
        }

        public bool HasConnection()
        {
            if (CommunicationSingleton.Instance.HasConnection) { return true; }

            // no connection
            if (CommunicationSingleton.Instance.connectToService() == 0)
            {
                // reproduce the (static) models
                l_model = new LogModel();
                c_model = new ConfigModel();
                h_model = new HomePageModel(c_model.configuration);
                p_model = new PhotosModel(c_model.configuration);
                return true;
            }
            else { return false; }
        }
    }
}

ImageServiceWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My Image Service Application</title>
    <link rel="shortcut icon" href="https://pbs.twimg.com/profile_images/598037887247130624/BK9nn-_D_400x400.jpg" type="image/jpg" />
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>

    <script src="~/Scripts/jquery-3.0.0.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Image Service", "HomePage", "Web", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Configuration", "ConfigView", "Web")</li>
                    <li>@Html.ActionLink("Photos", "PhotosView", "Web")</li>
                    <li>@Html.ActionLink("Logs", "LogsView", "Web")</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My Image Service Application</p>
        </footer>
    </div>

</body>
</html>